### ISSUE TITLE
Update project repositories

### ISSUE THREAD

**Issue by ChristianFrisson** [WHC2021SIC/WHC2021SIC-ProjectTemplate#1]
# Tasks
- Add team members information: names, pictures, websites, pronouns, biographies
- Merge information from your proposal: abstract, description
- Review your team’s sensors configuration that @WHC2021SIC/sic-chairs sketched for teams

# Teams
- [x] https://github.com/WHC2021SIC/WHC2021SIC-TeamCyborgCrafts/issues/1
- [ ] https://github.com/WHC2021SIC/WHC2021SIC-TeamMusicalArmband/issues/1
- [x] https://github.com/WHC2021SIC/WHC2021SIC-TeamOnBodyGym/issues/1
- [ ] https://github.com/WHC2021SIC/WHC2021SIC-TeamTactileMirror/issues/1
- [x] https://github.com/WHC2021SIC/WHC2021SIC-TeamVibroraptile/issues/1
- [x] https://github.com/WHC2021SIC/WHC2021SIC-TeamVibrotactileDataPhysicalization/issues/1
